data:
  dataset: 'ZeroShot_Imgft_Lang_Dataset'
  cohort: 'NLST.train'
  img_dim: 512
  expr_dim: 1024
  date_format: "%Y%m%d"
  val_split: 0
  label: "outcome_unconfirmed"
  compute_text_embeddings: False

logging:
  log_every_n_steps: 2
  val_every_n_epochs: 1
  verbosity: 0

model:
  model_name: 'clip_zeroshot_classifier'
  embed_dim: 256
  transformer_width: 256
  slen: 3
  encoder_ckpt: "./model_best-epoch=9002-loss=0.022.pth"

trainer:
  trainer_name: 'FinetuneCLIPTrainer'
  batch_size: 2401 # 6500
  lr: !!float 1e-3
  epochs: 2000
  save_period: 100
  monitor: 'max val/auc'
  resume: null
  warmup: 40
  n_gpu: 1
  predict_as_onehot: True