data:
  dataset: 'Imgft_Lang_Dataset'
  cohort: 'NLST.train'
  img_dim: 512
  expr_dim: 1024
  date_format: "%Y%m%d"
  val_split: 0
  label: "outcome_unconfirmed"

logging:
  log_every_n_steps: 10
  val_every_n_epochs: 1
  verbosity: 0

model:
  model_name: 'clip_base'
  embed_dim: 256
  transformer_width: 256
  slen: 3

trainer:
  trainer_name: 'CLIPTrainer'
  batch_size: 2401 # 6500
  lr: !!float 1e-3
  epochs: 10000
  save_period: 500
  monitor: 'min loss'
  resume: null
  warmup: 1000
  n_gpu: 1