data:
  dataset: 'Imgft_Dataset'
  cohort: 'NLST.train'
  img_dim: 512
  expr_dim: 13
  date_format: "%Y%m%d"
  val_split: 0
  # label: "cancer_year1"
  label: "cancer_year1_unconfirmed"

logging:
  log_every_n_steps: 2
  val_every_n_epochs: 4
  verbosity: 0

model:
  model_name: 'img_classifier'
  embed_dim: 256
  transformer_width: 256
  slen: 1
  classifier_depth: 1

trainer:
  trainer_name: 'FinetuneCLIPTrainer'
  batch_size: 2401 # 6500
  lr: !!float 1e-3
  encoder_lr: null
  epochs: 1000
  save_period: 100
  monitor: 'max val/auc'
  resume: null
  warmup: 40
  n_gpu: 1
  predict_as_onehot: True
